// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using websuli.Models;

namespace websuli.Migrations
{
    [DbContext(typeof(websuliContext))]
    [Migration("20191130231216_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("websuli.Model.Feladat", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("FeladatsorID");

                    b.Property<string>("Gyerekvalasz");

                    b.Property<string>("Helyesvalasz");

                    b.Property<int>("ValaszidoSec");

                    b.Property<int>("eredmeny");

                    b.Property<string>("feladatJson");

                    b.Property<string>("feladatText");

                    b.HasKey("ID");

                    b.HasIndex("FeladatsorID");

                    b.ToTable("Feladatok");
                });

            modelBuilder.Entity("websuli.Model.Feladatsor", b =>
                {
                    b.Property<Guid>("FeladatsorID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("cnt");

                    b.Property<int>("eredmenypct");

                    b.Property<string>("feladatTipus");

                    b.Property<int>("feladatszam");

                    b.Property<string>("gyerek")
                        .HasMaxLength(50);

                    b.Property<int>("helyescnt");

                    b.Property<int>("hibascnt");

                    b.Property<DateTime>("kiadasDatum");

                    b.Property<string>("sornev");

                    b.HasKey("FeladatsorID");

                    b.ToTable("Feladatsor");
                });

            modelBuilder.Entity("websuli.Model.Feladat", b =>
                {
                    b.HasOne("websuli.Model.Feladatsor", "Feladatsor")
                        .WithMany()
                        .HasForeignKey("FeladatsorID");
                });
#pragma warning restore 612, 618
        }
    }
}
